trigger:
  branches:
    include:
      - main
      - dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: '<YOUR_AZURE_SERVICE_CONNECTION>'
  resourceGroup: '<YOUR_RESOURCE_GROUP>'
  location: 'eastus'
  functionAppName: 'crudapifunc'
  bicepFile: 'main.bicep'

stages:
  - stage: BuildAndTest
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
          - script: npm install
            displayName: 'Install dependencies'
          - script: npm test
            displayName: 'Run tests'

  - stage: DeployInfra
    jobs:
      - deployment: DeployBicep
        environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: '$(azureSubscription)'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      az deployment group create \
                        --resource-group $(resourceGroup) \
                        --template-file $(bicepFile) \
                        --parameters prefix=crudapi location=$(location)

  - stage: DeployFunctions
    dependsOn: DeployInfra
    jobs:
      - deployment: DeployFunc
        environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureFunctionApp@2
                  inputs:
                    azureSubscription: '$(azureSubscription)'
                    appType: 'functionApp'
                    appName: '$(functionAppName)'
                    package: '$(System.DefaultWorkingDirectory)' 